# Generated by Django 5.1.4 on 2024-12-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_user_alter_review_user_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
