# Generated by Django 5.1.4 on 2024-12-13 10:54

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="products/", validators=[product.models.validate_image_format]
            ),
        ),
    ]
