# Generated by Django 5.1.4 on 2024-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_price_product_new_price_product_old_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons/")),
            ],
        ),
    ]
