# Generated by Django 5.1.4 on 2024-12-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
