# Generated by Django 5.1.4 on 2024-12-15 19:24

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_icon_category_image_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', validators=[category.models.validate_image_format]),
        ),
    ]
