# Generated by Django 5.1.4 on 2024-12-16 08:44

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', validators=[category.models.validate_image_format]),
        ),
    ]
